### ISSUE TITLE
Meta tag's content attribute breaks build

### ISSUE THREAD

**Issue by bongofury** [TylorS/typed-content-hash#5]
Hello,

I found out that any meta tag that has a content attribute containing a ``.`` is recognized as a path to a file.
So the build breaks, for example, in these two common scenarios:

```html
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  ...
</head>
```

and

```html
<head>
  <meta name="description" content="This is my site. It's very cool!">
  ...
</head>
```

More details here https://github.com/TylorS/snowpack-plugin-hash/issues/9 .

**Comment by TylorS** [comment]
Hey @bongofury Many thanks for taking the time to open a bug report, it really helps.

This definitely seems like an oversight. I honestly copied that [searchMap from another project](https://github.com/posthtml/posthtml-urls/blob/master/lib/defaultOptions.js#L34) I was using previously and looking back with this information I definitely lost a check that was being used there to determine if the meta.content could be a URL based on other attributes.

I could probably see 2 options. The option you proposed directly in your PR, and then also picking back up the logic that was originally lost. I can open a PR to see what the differences might look like. I'm guessing the latter case doesn't impact you presently (me either), but it does seem slightly more robust. Any thoughts on those options?

**Comment by TylorS** [comment]
Hey @bongofury I opened that PR, if you have a moment to take a look or maybe try the code changes yourself, that'd be really helpful. https://github.com/TylorS/typed-content-hash/pull/7

**Comment by TylorS** [comment]
I added a test to #7 which places `<meta name="viewport" content="width=device-width, initial-scale=1.0">` into my test directory so we can be pretty sure we don't regress on this use-case.

**Comment by TylorS** [comment]
Alrighty...after double checking this you're indeed 100% correct we should be able to skip these tags entirely. Since `http-equiv=refresh` with a URL is to create a redirect, it doesn't really make sense to have that value be anything other than something external or another HTML file which will never get rewritten with a content hash to begin with. With that in mind I'm going to go ahead and kill #7 and merge your PR.

Thanks for bearing with me, but I just wanted to understand everything myself 😄

**Comment by TylorS** [comment]
v0.6.3  is published with your fix, many thanks @bongofury !! I hope the library proves useful to you

**Comment by bongofury** [comment]
Well done @TylorS, I'm currently using the new version and everything's OK.
Thank you for your work, glad to help!
